name: payment_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_credit_card:
    git:
      url: https://github.com/Sebastian0002/flutter_credit_card.git
      ref: master
  flutter_launcher_icons: ^0.14.2
  flutter_stripe: ^11.3.0
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  meta: ^1.15.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
